# 船体（Hull）のマスターデータ
HULL_DATA = {
    "駆逐艦": [
        {"name": "のぶしゃお", "atk": 0, "def": 5, "hp": 120,
            "spd": 100, "sp": 3, "rarity": "N", "category": "駆逐艦"},
        {"name": "磯風", "atk": 0, "def": 20, "hp": 150, "spd": 180,
            "sp": 5, "rarity": "R", "category": "駆逐艦"},
        {"name": "峯風", "atk": 0, "def": 15, "hp": 170, "spd": 190,
            "sp": 5, "rarity": "R", "category": "駆逐艦"},
        {"name": "睦月", "atk": 0, "def": 18, "hp": 170, "spd": 185,
            "sp": 3, "rarity": "N", "category": "駆逐艦"},
        {"name": "初春", "atk": 0, "def": 22, "hp": 140, "spd": 175,
            "sp": 5, "rarity": "R", "category": "駆逐艦"},
        {"name": "吹雪", "atk": 0, "def": 50, "hp": 350, "spd": 140,
            "sp": 10, "rarity": "SR", "category": "駆逐艦"},
        {"name": "陽炎", "atk": 0, "def": 20, "hp": 200, "spd": 230,
            "sp": 10, "rarity": "SR", "category": "駆逐艦"},
        {"name": "夕雲", "atk": 0, "def": 30, "hp": 300, "spd": 345,
            "sp": 10, "rarity": "SR", "category": "駆逐艦"},
        {"name": "ベンソン", "atk": 0, "def": 50, "hp": 300, "spd": 160,
            "sp": 10, "rarity": "SR", "category": "駆逐艦"},
        {"name": "朝潮", "atk": 0, "def": 15, "hp": 200, "spd": 170,
            "sp": 5, "rarity": "R", "category": "駆逐艦"},
        {"name": "Z1", "atk": 0, "def": 50, "hp": 400, "spd": 150,
            "sp": 10, "rarity": "SR", "category": "駆逐艦"},
        {"name": "朱雀", "atk": 0, "def": 40, "hp": 1000, "spd": 350,
            "sp": 20, "rarity": "SSR", "category": "駆逐艦"},
    ],
    "軽巡洋艦": [
        {"name": "のぶお", "atk": 0, "def": 10, "hp": 130, "spd": 50,
            "sp": 3, "rarity": "N", "category": "軽巡洋艦"},
        {"name": "天龍", "atk": 0, "def": 20, "hp": 200, "spd": 100,
            "sp": 3, "rarity": "N", "category": "軽巡洋艦"},
        {"name": "球磨", "atk": 0, "def": 30, "hp": 300, "spd": 120,
            "sp": 5, "rarity": "R", "category": "軽巡洋艦"},
        {"name": "大淀(1943)", "atk": 0, "def": 50, "hp": 350,
         "spd": 100, "sp": 10, "rarity": "SR", "category": "軽巡洋艦"},
        {"name": "セントルイス", "atk": 0, "def": 40, "hp": 300,
            "spd": 120, "sp": 5, "rarity": "R", "category": "軽巡洋艦"},
        {"name": "リアンダー", "atk": 0, "def": 60, "hp": 450, "spd": 200,
            "sp": 10, "rarity": "SR", "category": "軽巡洋艦"},
        {"name": "エディンバラ", "atk": 0, "def": 50, "hp": 500,
            "spd": 230, "sp": 10, "rarity": "SR", "category": "軽巡洋艦"},
        {"name": "疾風", "atk": 0, "def": 70, "hp": 1500, "spd": 250,
            "sp": 20, "rarity": "SSR", "category": "軽巡洋艦"},
    ],
    "重巡洋艦": [
        {"name": "ヘビーのぶお", "atk": 0, "def": 20, "hp": 200,
            "spd": 20, "sp": 3, "rarity": "N", "category": "重巡洋艦"},
        {"name": "古鷹", "atk": 0, "def": 50, "hp": 250, "spd": 60,
            "sp": 5, "rarity": "R", "category": "重巡洋艦"},
        {"name": "青葉", "atk": 0, "def": 50, "hp": 250, "spd": 50,
            "sp": 5, "rarity": "R", "category": "重巡洋艦"},
        {"name": "AH(1945)", "atk": 0, "def": 150, "hp": 800,
         "spd": 30, "sp": 20, "rarity": "SSR", "category": "重巡洋艦"},
        {"name": "ボルチモア", "atk": 0, "def": 50, "hp": 400, "spd": 60,
            "sp": 10, "rarity": "SR", "category": "重巡洋艦"},
        {"name": "ウィチタ", "atk": 0, "def": 40, "hp": 350, "spd": 60,
            "sp": 10, "rarity": "SR", "category": "重巡洋艦"},
        {"name": "ノーザンプトン", "atk": 0, "def": 40, "hp": 400,
            "spd": 50, "sp": 5, "rarity": "R", "category": "重巡洋艦"},
        {"name": "ロキ", "atk": 0, "def": 50, "hp": 750, "spd": 80,
            "sp": 20, "rarity": "SSR", "category": "重巡洋艦"},
        {"name": "トール", "atk": 0, "def": 100, "hp": 1000, "spd": 70,
            "sp": 20, "rarity": "SSR", "category": "重巡洋艦"},
        {"name": "ドイッチュラント", "atk": 0, "def": 50, "hp": 450,
            "spd": 60, "sp": 10, "rarity": "SR", "category": "重巡洋艦"},
    ],
    "戦艦": [
        {"name": "大高専", "atk": 0, "def": 1000, "hp": 3000, "spd": 50,
            "sp": 30, "rarity": "LEGEND", "category": "戦艦"},
        {"name": "敷島", "atk": 0, "def": 70, "hp": 500,
            "spd": 20, "sp": 5, "rarity": "R", "category": "戦艦"},
        {"name": "薩摩", "atk": 0, "def": 80, "hp": 500,
            "spd": 25, "sp": 5, "rarity": "R", "category": "戦艦"},
        {"name": "河内", "atk": 0, "def": 80, "hp": 500,
            "spd": 20, "sp": 5, "rarity": "R", "category": "戦艦"},
        {"name": "金剛", "atk": 0, "def": 100, "hp": 800, "spd": 20,
            "sp": 10, "rarity": "SR", "category": "戦艦"},
        {"name": "伊勢", "atk": 0, "def": 100, "hp": 750, "spd": 25,
            "sp": 10, "rarity": "SR", "category": "戦艦"},
        {"name": "長門", "atk": 0, "def": 150, "hp": 1000,
            "spd": 40, "sp": 10, "rarity": "SR", "category": "戦艦"},
        {"name": "大和(1944)", "atk": 0, "def": 300, "hp": 1200,
         "spd": 30, "sp": 20, "rarity": "SSR", "category": "戦艦"},
        {"name": "改大和", "atk": 0, "def": 330, "hp": 1440,
            "spd": 35, "sp": 20, "rarity": "SSR", "category": "戦艦"},
        {"name": "超大和", "atk": 0, "def": 400, "hp": 1500, "spd": 40,
            "sp": 30, "rarity": "LEGEND", "category": "戦艦"},
        {"name": "ビスマルク", "atk": 0, "def": 250, "hp": 900,
            "spd": 70, "sp": 20, "rarity": "SSR", "category": "戦艦"},
        {"name": "十三号", "atk": 0, "def": 200, "hp": 850, "spd": 100,
            "sp": 20, "rarity": "SSR", "category": "戦艦"},
        {"name": "ノースカロライナ", "atk": 0, "def": 300, "hp": 1000,
            "spd": 50, "sp": 10, "rarity": "SR", "category": "戦艦"},
        {"name": "サウスダコタ", "atk": 0, "def": 350, "hp": 900,
            "spd": 40, "sp": 10, "rarity": "SR", "category": "戦艦"},
        {"name": "アイオワ", "atk": 0, "def": 400, "hp": 1000,
            "spd": 30, "sp": 20, "rarity": "SSR", "category": "戦艦"},
        {"name": "フッド", "atk": 0, "def": 300, "hp": 700,
            "spd": 60, "sp": 10, "rarity": "SR", "category": "戦艦"},
        {"name": "ネルソン", "atk": 0, "def": 200, "hp": 800,
            "spd": 50, "sp": 10, "rarity": "SR", "category": "戦艦"},
        {"name": "KGV", "atk": 0, "def": 400, "hp": 1300,
            "spd": 10, "sp": 20, "rarity": "SSR", "category": "戦艦"},
        {"name": "バイエルン", "atk": 0, "def": 200, "hp": 600,
            "spd": 40, "sp": 5, "rarity": "R", "category": "戦艦"},
        {"name": "紀伊", "atk": 0, "def": 250, "hp": 900, "spd": 50,
            "sp": 10, "rarity": "SR", "category": "戦艦"},
        {"name": "H43", "atk": 0, "def": 300, "hp": 1000,
            "spd": 20, "sp": 20, "rarity": "SSR", "category": "戦艦"},
        {"name": "O級", "atk": 0, "def": 300, "hp": 700, "spd": 10,
            "sp": 10, "rarity": "SR", "category": "戦艦"},
        {"name": "プロメテウス", "atk": 0, "def": 500, "hp": 500,
            "spd": 350, "sp": 0, "rarity": "SSR", "category": "戦艦"},
        {"name": "ジャガーノート", "atk": 0, "def": 1500, "hp": 9999,
            "spd": 20, "sp": 30, "rarity": "LEGEND", "category": "戦艦"},
    ],
    "空母": [
        {"name": "メイドイン学友会", "atk": 0, "def": 150, "hp": 1500,
            "spd": 80, "sp": 150, "rarity": "SSR", "category": "空母"},
        {"name": "鳳翔", "atk": 0, "def": 20, "hp": 300, "spd": 40,
            "sp": 20, "rarity": "R", "category": "空母"},
        {"name": "大鷹", "atk": 0, "def": 25, "hp": 350, "spd": 35,
            "sp": 25, "rarity": "R", "category": "空母"},
        {"name": "蒼龍", "atk": 0, "def": 50, "hp": 600, "spd": 120,
            "sp": 60, "rarity": "SR", "category": "空母"},
        {"name": "飛龍", "atk": 0, "def": 50, "hp": 600, "spd": 130,
            "sp": 65, "rarity": "SR", "category": "空母"},
        {"name": "ミッドウェイ", "atk": 0, "def": 200, "hp": 2500, "spd": 60,
            "sp": 200, "rarity": "LEGEND", "category": "空母"},
        {"name": "信濃", "atk": 0, "def": 400, "hp": 3500, "spd": 40,
            "sp": 100, "rarity": "SSR", "category": "空母"},
        {"name": "大鳳", "atk": 0, "def": 300, "hp": 1800, "spd": 90,
            "sp": 120, "rarity": "SSR", "category": "空母"},
        {"name": "イラストリアス", "atk": 0, "def": 250, "hp": 1500,
            "spd": 50, "sp": 80, "rarity": "SR", "category": "空母"},
        {"name": "ヨークタウン", "atk": 0, "def": 80, "hp": 1000,
            "spd": 100, "sp": 90, "rarity": "SR", "category": "空母"},
        {"name": "レキシントン", "atk": 0, "def": 90, "hp": 1200,
            "spd": 85, "sp": 95, "rarity": "SR", "category": "空母"},
        {"name": "GZ", "atk": 0, "def": 150, "hp": 1400,
            "spd": 110, "sp": 70, "rarity": "SR", "category": "空母"},
        {"name": "鳳凰", "atk": 0, "def": 100, "hp": 2000, "spd": 300,
            "sp": 250, "rarity": "LEGEND", "category": "空母"},
        {"name": "玉座", "atk": 0, "def": 180, "hp": 3000, "spd": 150,
            "sp": 300, "rarity": "LEGEND", "category": "空母"},
        {"name": "マザーシップ", "atk": 0, "def": 500, "hp": 8000, "spd": 10,
            "sp": 500, "rarity": "LEGEND", "category": "空母"},
    ]
}

MAIN_CANNONS = [
    {"name": "豆鉄砲", "atk": 5, "def": 0, "hp": 0, "spd": -2, "rarity": "N"},
    {"name": "パチンコ", "atk": 7, "def": 0, "hp": 0, "spd": -1, "rarity": "N"},
    {"name": "100均の弓矢", "atk": 8, "def": 0, "hp": 0, "spd": -1, "rarity": "N"},
    {"name": "投石器(石ころサイズ)", "atk": 15, "def": 0,
     "hp": 0, "spd": -6, "rarity": "N"},
    {"name": "入れ歯", "atk": 3, "def": 0, "hp": 0, "spd": -1, "rarity": "N"},
    {"name": "段ボールキャノン", "atk": 4, "def": 0, "hp": 0, "spd": -2, "rarity": "N"},
    {"name": "輪ゴム鉄砲", "atk": 1, "def": 0, "hp": 0, "spd": -1, "rarity": "N"},
    {"name": "ドラ●エのメラ発射装置", "atk": 34, "def": 0,
        "hp": 0, "spd": -10, "rarity": "N"},
    {"name": "マイクラのディスペンサー", "atk": 38, "def": 0,
        "hp": 0, "spd": -15, "rarity": "N"},
    {"name": "鳩がまっすぐ飛んでいって戻ってこないタイプの鳩時計", "atk": 6,
        "def": 0, "hp": 0, "spd": -4, "rarity": "N"},
    {"name": "ピストル", "atk": 20, "def": 0, "hp": 0, "spd": -3, "rarity": "N"},
    {"name": "勢いの凄い水鉄砲", "atk": 2, "def": 0, "hp": 0, "spd": -2, "rarity": "N"},
    {"name": "単装砲(小)", "atk": 40, "def": 0, "hp": 0,
     "spd": -20, "rarity": "R"},
    {"name": "海賊船の大砲", "atk": 35, "def": 5, "hp": 0, "spd": -25, "rarity": "R"},
    {"name": "タコ発射装置", "atk": 30, "def": 0, "hp": 0, "spd": -20, "rarity": "R"},
    {"name": "大型ボウガン", "atk": 25, "def": 0, "hp": 0, "spd": -15, "rarity": "R"},
    {"name": "スラ・ストライク発射機", "atk": 50, "def": 0,
        "hp": 10, "spd": -30, "rarity": "R"},
    {"name": "頭矢場式自動小銃", "atk": 45, "def": 0, "hp": 0, "spd": -22, "rarity": "R"},
    {"name": "輪ゴム400本分のゴム鉄砲", "atk": 25, "def": 0,
        "hp": 0, "spd": -10, "rarity": "R"},
    {"name": "投石器+てつはう", "atk": 60, "def": 0, "hp": 0, "spd": -35, "rarity": "R"},
    {"name": "発射可能なクリーパー", "atk": 55, "def": -
        10, "hp": 0, "spd": -30, "rarity": "R"},
    {"name": "100V直流電源レーザー砲", "atk": 70, "def": 0,
        "hp": 0, "spd": -40, "rarity": "R"},
    {"name": "緑星・ドクロ爆発草", "atk": 65, "def": 0, "hp": 0, "spd": -38, "rarity": "R"},
    {"name": "音速で発射される三角定規", "atk": 42, "def": 0,
        "hp": 0, "spd": -25, "rarity": "R"},
    {"name": "連装砲", "atk": 80, "def": 5, "hp": 0, "spd": -40, "rarity": "SR"},
    {"name": "劣化ウラン弾", "atk": 90, "def": 0, "hp": 0, "spd": -45, "rarity": "SR"},
    {"name": "大型海賊船の大砲", "atk": 85, "def": 10,
        "hp": 20, "spd": -42, "rarity": "SR"},
    {"name": "レールガン", "atk": 110, "def": 0, "hp": 0, "spd": -55, "rarity": "SR"},
    {"name": "マッハ20で飛ぶデコポン", "atk": 95, "def": 0,
        "hp": 0, "spd": -48, "rarity": "SR"},
    {"name": "ガトリングガン", "atk": 120, "def": 0, "hp": 0, "spd": -60, "rarity": "SR"},
    {"name": "磁石砲", "atk": 105, "def": 5, "hp": 0, "spd": -50, "rarity": "SR"},
    {"name": "ドラ●エのメラゾーマ発射装置", "atk": 130, "def": 0,
        "hp": 0, "spd": -65, "rarity": "SR"},
    {"name": "TNTキャノン", "atk": 115, "def": -20,
        "hp": 0, "spd": -58, "rarity": "SR"},
    {"name": "混ぜるな危険の洗剤混ぜたやつ", "atk": 100, "def": 0,
        "hp": 0, "spd": -50, "rarity": "SR"},
    {"name": "クソデカネイルガン", "atk": 125, "def": 0,
        "hp": 0, "spd": -62, "rarity": "SR"},
    {"name": "ロケットランチャー", "atk": 118, "def": 0,
        "hp": 0, "spd": -59, "rarity": "SR"},
    {"name": "三連装砲(大)", "atk": 180, "def": 20, "hp": 50,
     "spd": -80, "rarity": "SSR"},
    {"name": "46cm主砲(!?)", "atk": 250, "def": 30, "hp": 100,
     "spd": -120, "rarity": "SSR"},
    {"name": "巨大レールガン", "atk": 300, "def": 10,
        "hp": 0, "spd": -150, "rarity": "SSR"},
    {"name": "電磁誘導キャノン", "atk": 280, "def": 15,
        "hp": 0, "spd": -140, "rarity": "SSR"},
    {"name": "超大型海賊船の大砲", "atk": 200, "def": 50,
        "hp": 200, "spd": -100, "rarity": "SSR"},
    {"name": "連装ガトリング砲", "atk": 350, "def": 0,
        "hp": 0, "spd": -180, "rarity": "SSR"},
    {"name": "超高圧ニトロ砲", "atk": 320, "def": -50,
        "hp": 0, "spd": -160, "rarity": "SSR"},
    {"name": "単位砲", "atk": 220, "def": 0, "hp": 0, "spd": -110, "rarity": "SSR"},
    {"name": "巨大ロケットランチャー", "atk": 260, "def": 0,
        "hp": 50, "spd": -130, "rarity": "SSR"},
    {"name": "光子力ビーム", "atk": 500, "def": 100,
        "hp": 200, "spd": -200, "rarity": "LEGEND"},
    {"name": "反物質レーザー「アンチ・スパイラル」", "atk": 600, "def": 200,
        "hp": 300, "spd": -250, "rarity": "LEGEND"},
    {"name": "ビーム・マグナム", "atk": 550, "def": 150,
        "hp": 200, "spd": -220, "rarity": "LEGEND"},
    {"name": "閃光の槍", "atk": 700, "def": 50,
        "hp": 100, "spd": -300, "rarity": "LEGEND"},
    {"name": "AMドライブ搭載型6連装円形バレル搭載複合殲滅システム", "atk": 9000,
        "def": 1000, "hp": 2000, "spd": -180, "rarity": "LEGEND"},
    {"name": "ソーラーレイ", "atk": 800, "def": 300,
        "hp": 500, "spd": -350, "rarity": "LEGEND"},
    {"name": "芽ネギ(うますぎて破壊力を持った)", "atk": 1000, "def": 500,
     "hp": 1000, "spd": -500, "rarity": "LEGEND"},
]

SECONDARY_CANNONS = [
    {"name": "石ころ投石機", "atk": 5, "def": 0, "hp": 0, "spd": -2, "rarity": "N"},
    {"name": "ビー●マン", "atk": 1, "def": 0, "hp": 0, "spd": -1, "rarity": "N"},
    {"name": "竹筒水鉄砲", "atk": 2, "def": 0, "hp": 0, "spd": -1, "rarity": "N"},
    {"name": "アーチェリーのオリンピック金メダル獲得選手", "atk": 7,
        "def": 0, "hp": 0, "spd": -3, "rarity": "N"},
    {"name": "14cm単装副砲", "atk": 10, "def": 0, "hp": 0, "spd": -5, "rarity": "R"},
    {"name": "小型ガトリングガン", "atk": 15, "def": 0, "hp": 0, "spd": -8, "rarity": "R"},
    {"name": "15.5cm三連装副砲", "atk": 25, "def": 2,
        "hp": 0, "spd": -10, "rarity": "R"},
    {"name": "10cm高角砲", "atk": 20, "def": 0, "hp": 0, "spd": -12, "rarity": "R"},
    {"name": "対空レーザー砲", "atk": 40, "def": 5, "hp": 0, "spd": -20, "rarity": "SR"},
    {"name": "小型レールガン", "atk": 50, "def": 0, "hp": 0, "spd": -25, "rarity": "SR"},
    {"name": "量子加速砲", "atk": 80, "def": 10, "hp": 0, "spd": -40, "rarity": "SSR"},
    {"name": "反物質副砲", "atk": 150, "def": 20,
        "hp": 50, "spd": -60, "rarity": "LEGEND"},
    {"name": "両津勘吉(野球ボール装備)", "atk": 500, "def": 100,
     "hp": 1000, "spd": -200, "rarity": "LEGEND"},
]

ANTI_AIR = [
    {"name": "虫取り網", "atk": 1, "def": 1, "hp": 0, "spd": -1, "rarity": "N"},
    {"name": "ハエたたき", "atk": 2, "def": 0, "hp": 0, "spd": -1, "rarity": "N"},
    {"name": "ただの竹竿", "atk": 1, "def": 2, "hp": 0, "spd": -2, "rarity": "N"},
    {"name": "全力の威嚇(声のみ)", "atk": 0, "def": 3,
     "hp": 0, "spd": 0, "rarity": "N"},
    {"name": "25mm三連装機銃", "atk": 8, "def": 10, "hp": 0, "spd": -5, "rarity": "R"},
    {"name": "打ち上げ花火100連発", "atk": 15, "def": 5, "hp": 0, "spd": -8, "rarity": "R"},
    {"name": "高性能散弾銃", "atk": 12, "def": 12, "hp": 0, "spd": -6, "rarity": "R"},
    {"name": "訓練された鷹", "atk": 20, "def": 5, "hp": 0, "spd": 5, "rarity": "R"},
    {"name": "ボフォース40mm機関砲", "atk": 25, "def": 30,
        "hp": 20, "spd": -15, "rarity": "SR"},
    {"name": "自動追尾式ボウガン", "atk": 30, "def": 20,
        "hp": 0, "spd": -10, "rarity": "SR"},
    {"name": "超高音域スピーカー", "atk": 10, "def": 40,
        "hp": 0, "spd": -12, "rarity": "SR"},
    {"name": "高性能20mmCIWS", "atk": 60, "def": 80,
        "hp": 50, "spd": -30, "rarity": "SSR"},
    {"name": "電磁パルス発生装置", "atk": 40, "def": 120,
        "hp": 0, "spd": -40, "rarity": "SSR"},
    {"name": "VLS(垂直ミサイル発射システム)", "atk": 100, "def": 50,
     "hp": 20, "spd": -50, "rarity": "SSR"},
    {"name": "重力レンズ防壁", "atk": 150, "def": 500,
        "hp": 200, "spd": -80, "rarity": "LEGEND"},
    {"name": "絶対零度噴射装置", "atk": 300, "def": 300,
        "hp": 100, "spd": -100, "rarity": "LEGEND"},
    {"name": "蚊取り線香", "atk": 500, "def": 1000,
        "hp": 500, "spd": -200, "rarity": "LEGEND"},
]

BRIDGE_DATA = [
    {"name": "帆", "atk": 0, "def": 5, "hp": 50, "spd": 10, "sp": 0, "rarity": "N"},
    {"name": "敷島型艦橋", "atk": 5, "def": 20, "hp": 100,
        "spd": -5, "sp": 10, "rarity": "R"},
    {"name": "金剛型改装艦橋", "atk": 10, "def": 40,
        "hp": 200, "spd": 0, "sp": 30, "rarity": "SR"},
    {"name": "長門型屈曲煙突艦橋", "atk": 15, "def": 60,
        "hp": 250, "spd": -5, "sp": 40, "rarity": "SR"},
    {"name": "O級計画艦橋", "atk": 20, "def": 50, "hp": 220,
        "spd": 10, "sp": 35, "rarity": "SR"},
    {"name": "大和型塔状艦橋", "atk": 30, "def": 150, "hp": 500,
        "spd": -10, "sp": 80, "rarity": "SSR"},
    {"name": "E+Iコース製特注精密艦橋", "atk": 100, "def": 300,
        "hp": 1000, "spd": 50, "sp": 250, "rarity": "LEGEND"},
]

CAPTAINS = [
    {"name": "なんJ民", "atk": 5, "def": 5, "hp": 50, "spd": 5, "sp": 5, "rarity": "N"},
    {"name": "留年を恐れる学生", "atk": 0, "def": 100,
        "hp": 10, "spd": 100, "sp": 0, "rarity": "R"},
    {"name": "東郷平八郎", "atk": 50, "def": 50, "hp": 200,
        "spd": 10, "sp": 100, "rarity": "SR"},
    {"name": "山口多聞", "atk": 100, "def": 20, "hp": 150,
        "spd": 30, "sp": 150, "rarity": "SSR"},
    {"name": "勇者ロト", "atk": 200, "def": 200, "hp": 500,
        "spd": 50, "sp": 500, "rarity": "LEGEND"},
]

ARMOR = [
    {"name": "段ボール", "atk": 0, "def": 2, "hp": 10, "spd": 5, "sp": 0, "rarity": "N"},
    {"name": "強化プラスチック", "atk": 0, "def": 20,
        "hp": 100, "spd": -5, "sp": 0, "rarity": "R"},
    {"name": "CNC切削アルミ板", "atk": 0, "def": 80,
        "hp": 300, "spd": -15, "sp": 10, "rarity": "SR"},
    {"name": "対46cm砲重装甲", "atk": 0, "def": 300,
        "hp": 1000, "spd": -100, "rarity": "SSR"},
    {"name": "オリハルコン", "atk": 50, "def": 1500, "hp": 5000,
        "spd": 0, "sp": 100, "rarity": "LEGEND"},
]

ENGINES = [
    {"name": "人力(漕ぐタイプ)", "atk": 0, "def": 0, "hp": 0,
     "spd": 10, "sp": 0, "rarity": "N"},
    {"name": "スターリングエンジン", "atk": 0, "def": 5,
        "hp": 50, "spd": 30, "sp": 0, "rarity": "R"},
    {"name": "ガスタービンエンジン", "atk": 0, "def": 10,
        "hp": 100, "spd": 100, "sp": 10, "rarity": "SR"},
    {"name": "核融合炉", "atk": 50, "def": 50, "hp": 200,
        "spd": 250, "sp": 100, "rarity": "SSR"},
    {"name": "ミニブラックホール", "atk": 200, "def": 100, "hp": 500,
        "spd": 800, "sp": 300, "rarity": "LEGEND"},
]

SPECIAL_ITEMS = [
    {"name": "幸運の錨", "atk": 0, "def": 0, "hp": 0,
        "spd": 0, "sp": 50, "rarity": "R"},
    {"name": "お守り(必勝祈願)", "atk": 10, "def": 10, "hp": 10,
     "spd": 10, "sp": 10, "rarity": "N"},
    {"name": "緊急修復ツール", "atk": 0, "def": 50,
        "hp": 500, "spd": 0, "sp": 0, "rarity": "SR"},
    {"name": "たこ焼き", "atk": 100, "def": 0, "hp": 0,
        "spd": 150, "sp": 50, "rarity": "SSR"},
    {"name": "350単位", "atk": 300, "def": 300, "hp": 1000,
        "spd": 100, "sp": 400, "rarity": "LEGEND"},
]

SKILL_CASSETTES = [
    {"name": "基本戦術(突撃)", "atk": 20, "def": 0, "hp": 0,
     "spd": 10, "sp": 20, "rarity": "N"},
    {"name": "自動修復プログラム", "atk": 0, "def": 30,
        "hp": 200, "spd": 0, "sp": 50, "rarity": "R"},
    {"name": "一斉掃射の極意", "atk": 150, "def": 0, "hp": 0,
        "spd": -20, "sp": 100, "rarity": "SR"},
    {"name": "全方位バリア", "atk": 0, "def": 500, "hp": 500,
        "spd": 0, "sp": 200, "rarity": "SSR"},
    {"name": "核発射", "atk": 1000, "def": 0, "hp": 0,
        "spd": 0, "sp": 1000, "rarity": "LEGEND"},
]

ALL_PARTS = {
    "hull": HULL_DATA,
    "main_cannon": MAIN_CANNONS,
    "secondary_cannon": SECONDARY_CANNONS,
    "anti_air": ANTI_AIR,
    "bridge": BRIDGE_DATA,
    "captain": CAPTAINS,
    "armor": ARMOR,
    "engine": ENGINES,
    "item": SPECIAL_ITEMS,
    "skill": SKILL_CASSETTES
}
